plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.myheart.core.utils'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdk rootProject.ext.minSdkVersion
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility rootProject.ext.jdkVersion
        targetCompatibility rootProject.ext.jdkVersion
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}
dependencies {
    implementation 'com.google.android.gms:play-services-basement:18.10.0'
    implementation "androidx.core:core-ktx:1.16.0"
    implementation platform("org.jetbrains.kotlin:kotlin-bom:1.9.25")
    implementation 'com.google.code.gson:gson:2.10'
}
