plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
}

android {
    namespace 'com.myheart.core.sdk'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdk rootProject.ext.minSdkVersion
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildFeatures {
        buildConfig true
        aidl true
        dataBinding true
    }

    compileOptions {
        sourceCompatibility rootProject.ext.jdkVersion
        targetCompatibility rootProject.ext.jdkVersion
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation project(':aidl')
    implementation project(':utils')
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.4'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.8.4'
    implementation 'androidx.appcompat:appcompat:1.7.1'
}
