plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.myheart.core.aidl'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdk rootProject.ext.minSdkVersion
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildFeatures {
        aidl true
    }

    compileOptions {
        sourceCompatibility rootProject.ext.jdkVersion
        targetCompatibility rootProject.ext.jdkVersion
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation project(':utils')
}
